### ISSUE TITLE
Traceback: FileNotFoundError for opennft/plugins

### ISSUE THREAD

**Issue by seralouk** [OpenNFT/OpenNFT#111]
Hi there,

I have installed the Opennft on my MacBook using Matlab2019b and following the instruction found [here](https://opennft.readthedocs.io/en/latest/install.html). Everything seems to be working (`opennft` command works) and I am able to lunch the interface. However, after clicking on "Initialize", I get the following traceback:

```
seralouk:Desktop makis$ opennft
2021-07-01 04:14:54 | WARNING   | runmatlab:connect_to_matlab - Cannot connect to Matlab "MATLAB_NFB_MAIN"
2021-07-01 04:14:54 | WARNING   | opennft:initialize - There is no main Matlab session yet. Press "Initialize" button.
2021-07-01 04:16:24 | INFO      | mlproc:_start_matlab - Starting Matlab engine "MATLAB_NFB_MAIN_74085" helper process 4730...
2021-07-01 04:16:30 | INFO      | mlproc:_start_matlab - Matlab engine "MATLAB_NFB_MAIN_74085" is started
2021-07-01 04:16:30 | INFO      | mlproc:_connect - Connected to Matlab engine "MATLAB_NFB_MAIN_74085"
2021-07-01 04:16:32 | INFO      | mlproc:_start_matlab - Starting Matlab engine "MATLAB_NFB_SPM_74085" helper process 4793...
2021-07-01 04:16:36 | INFO      | mlproc:_start_matlab - Matlab engine "MATLAB_NFB_SPM_74085" is started
2021-07-01 04:16:36 | INFO      | mlproc:_connect - Connected to Matlab engine "MATLAB_NFB_SPM_74085"
2021-07-01 04:16:38 | INFO      | mlproc:_start_matlab - Starting Matlab engine "MATLAB_NFB_PTB_74085" helper process 4852...
2021-07-01 04:16:42 | INFO      | mlproc:_start_matlab - Matlab engine "MATLAB_NFB_PTB_74085" is started
2021-07-01 04:16:42 | INFO      | mlproc:_connect - Connected to Matlab engine "MATLAB_NFB_PTB_74085"
2021-07-01 04:16:42 | INFO      | opennft:initialize - Using Matlab session "MATLAB_NFB_MAIN_74085" as MAIN
2021-07-01 04:16:42 | INFO      | opennft:initialize - Using Matlab session "MATLAB_NFB_PTB_74085" for PTB
2021-07-01 04:16:42 | INFO      | opennft:initialize - Using Matlab session "MATLAB_NFB_SPM_74085" for SPM
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/opennft/opennft.py", line 381, in <lambda>
    self.btnInit.clicked.connect(lambda: self.initialize(start=True))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/opennft/opennft.py", line 1179, in initialize
    self.pluginWindow = plugin.PluginWindow()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/opennft/plugin.py", line 24, in __init__
    for p in [f for f in os.listdir(config.PLUGIN_PATH) if f.endswith('.py')]:
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/opennft/plugins'

```

I have tried to reinstall everything but this Traceback has not been resolved.

**Comment by ykoush** [comment]
@tiborauer please address and check that your plugins are compatible with recent updates.

**Comment by tiborauer** [comment]
I think the issue here is the installation. It says, it cannot find the "plugins" folder within the opennft installation.

**Comment by seralouk** [comment]
> I think the issue here is the installation. It says, it cannot find the "plugins" folder within the opennft installation.

I will try to re-install it once again and post here all the steps of the traceback is not resolved.

**Comment by seralouk** [comment]
I use Python3.7 specifically because the Matlab engine for python of Matlab2019b is not compatible with later python versions.

Installation steps: 
```
# opennft
python3.7 -m venv opennft-venv
source opennft-venv/bin/activate
python3.7 -m pip install -U pip setuptools wheel

pip3.7 install git+https://github.com/OpenNFT/OpenNFT.git

# engine
cd /Applications/MATLAB_R2019b.app/extern/engines/python
/Users/loukas/Desktop/opennft-venv/bin/python3.7 setup.py install


```
No errors. Clean installation output. `opennft` command opens the GUI. After clicking on "Initialize", I get the traceback (see OP) in the console. What else can I try? Interestingly, the GUI does not break.

**Comment by seralouk** [comment]
I solved the problem by manually copying the folder `plugins` to the location `/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/opennft/`. 

It should not be like that but there is no way to fix that with a clean new installation. I also lunch the GUI by simply using`opennft`.

```
which opennft
/Library/Frameworks/Python.framework/Versions/3.7/bin/opennft
```
After "Initialize" the output is smooth ! I also had to lunch the software outside the virtual enviroment.

```
seralouk:Desktop loukas$ opennft
2021-07-01 07:42:17 | WARNING   | runmatlab:connect_to_matlab - Cannot connect to Matlab "MATLAB_NFB_MAIN"
2021-07-01 07:42:17 | WARNING   | opennft:initialize - There is no main Matlab session yet. Press "Initialize" button.
2021-07-01 07:42:24 | INFO      | mlproc:_start_matlab - Starting Matlab engine "MATLAB_NFB_MAIN_08223" helper process 7489...
2021-07-01 07:42:30 | INFO      | mlproc:_start_matlab - Matlab engine "MATLAB_NFB_MAIN_08223" is started
2021-07-01 07:42:30 | INFO      | mlproc:_connect - Connected to Matlab engine "MATLAB_NFB_MAIN_08223"
2021-07-01 07:42:32 | INFO      | mlproc:_start_matlab - Starting Matlab engine "MATLAB_NFB_SPM_08223" helper process 7552...
2021-07-01 07:42:37 | INFO      | mlproc:_start_matlab - Matlab engine "MATLAB_NFB_SPM_08223" is started
2021-07-01 07:42:37 | INFO      | mlproc:_connect - Connected to Matlab engine "MATLAB_NFB_SPM_08223"
2021-07-01 07:42:39 | INFO      | mlproc:_start_matlab - Starting Matlab engine "MATLAB_NFB_PTB_08223" helper process 7612...
2021-07-01 07:42:44 | INFO      | mlproc:_start_matlab - Matlab engine "MATLAB_NFB_PTB_08223" is started
2021-07-01 07:42:44 | INFO      | mlproc:_connect - Connected to Matlab engine "MATLAB_NFB_PTB_08223"
2021-07-01 07:42:44 | INFO      | opennft:initialize - Using Matlab session "MATLAB_NFB_MAIN_08223" as MAIN
2021-07-01 07:42:44 | INFO      | opennft:initialize - Using Matlab session "MATLAB_NFB_PTB_08223" for PTB
2021-07-01 07:42:44 | INFO      | opennft:initialize - Using Matlab session "MATLAB_NFB_SPM_08223" for SPM
2021-07-01 07:42:44 | INFO      | opennft:initialize - Initialization finished (23.13 s)

**Comment by da0c** [comment]
We've fixed `setup.py` by adding the plugins folder in the package data.
Btw, note, that installing using `venv` is recommended.
