### ISSUE TITLE
Error about click "Load Setup File" icon.

### ISSUE THREAD

**Issue by brainwatcher** [OpenNFT/OpenNFT#119]
**Hi, I am trying to input demo setup ini file into the GUI window. I had click the `initial` icon and several Matlab related prompts appears in the terminal as below. I click `Review Parameters` and then `Load Setup File` icon. But no response came out in GUI window. In terminal, some error information came out.  It seems somthing wrong with my directory. But I can't figure it out. My python version is 3.7 in Windows10 64 bit. Could you give me some suggestions?** 
"

> (opennft-venv) C:\Users\psylab706\Documents\MATLAB\ZW\openNFT>python -m opennft

2021-07-27 10:26:55 | WARNING   | runmatlab:connect_to_matlab - Cannot connect to Matlab "MATLAB_NFB_MAIN"
2021-07-27 10:26:55 | WARNING   | opennft:initialize - There is no main Matlab session yet. Press "Initialize" button.
2021-07-27 10:27:01 | INFO      | mlproc:_start_matlab - Starting Matlab engine "MATLAB_NFB_MAIN_20411" helper process 6216...
2021-07-27 10:27:06 | INFO      | mlproc:_start_matlab - Matlab engine "MATLAB_NFB_MAIN_20411" is started
2021-07-27 10:27:07 | INFO      | mlproc:_connect - Connected to Matlab engine "MATLAB_NFB_MAIN_20411"
2021-07-27 10:27:08 | INFO      | mlproc:_start_matlab - Starting Matlab engine "MATLAB_NFB_SPM_20411" helper process 12492...
2021-07-27 10:27:15 | INFO      | mlproc:_start_matlab - Matlab engine "MATLAB_NFB_SPM_20411" is started
2021-07-27 10:27:15 | INFO      | mlproc:_connect - Connected to Matlab engine "MATLAB_NFB_SPM_20411"
2021-07-27 10:27:16 | INFO      | mlproc:_start_matlab - Starting Matlab engine "MATLAB_NFB_PTB_20411" helper process 2132...
2021-07-27 10:27:23 | INFO      | mlproc:_start_matlab - Matlab engine "MATLAB_NFB_PTB_20411" is started
2021-07-27 10:27:23 | INFO      | mlproc:_connect - Connected to Matlab engine "MATLAB_NFB_PTB_20411"
2021-07-27 10:27:23 | INFO      | opennft:initialize - Using Matlab session "MATLAB_NFB_MAIN_20411" as MAIN
2021-07-27 10:27:23 | INFO      | opennft:initialize - Using Matlab session "MATLAB_NFB_PTB_20411" for PTB
2021-07-27 10:27:23 | INFO      | opennft:initialize - Using Matlab session "MATLAB_NFB_SPM_20411" for SPM
2021-07-27 10:27:29 | INFO      | opennft:initialize - Initialization finished (28.21 s)

>  I click the  `Load Setup File` icon 

Traceback (most recent call last):
  File "C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\opennft-venv\lib\site-packages\opennft\opennft.py", line 1500, in onChooseSetFile
    self, "Select 'SET File'", self.settingFileName, 'ini files (*.ini)')[0]
TypeError: getOpenFileName(parent: QWidget = None, caption: str = '', directory: str = '', filter: str = '', initialFilter: str = '', options: Union[QFileDialog.Options, QFileDialog.Option] = 0): argument 3 has unexpected type 'WindowsPath'
"

**For more information, I also try to click the other file loaded icons. Among them, only `Protocal File` and `SVM Weights` pop up a file choice window. The others, like `work Folder`, `MRI Watch Folder` ,`ROI Folder`, `DCMROI Folder` , `Underlay Structural File` and `Motion Correction Template` gives the similar errors about `WindowsPath`. The error is as below.**

"
Traceback (most recent call last):
  File "C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\opennft-venv\lib\site-packages\opennft\opennft.py", line 409, in <lambda>
    lambda: self.onChooseFolder('WorkFolder', self.leWorkFolder))
  File "C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\opennft-venv\lib\site-packages\opennft\opennft.py", line 1596, in onChooseFolder
    self, "Select '{}' directory".format(name), config.ROOT_PATH)
TypeError: getExistingDirectory(parent: QWidget = None, caption: str = '', directory: str = '', options: Union[QFileDialog.Options, QFileDialog.Option] = QFileDialog.ShowDirsOnly): argument 3 has unexpected type 'WindowsPath
"

**Comment by TheAmid** [comment]
Thanks for finding! I fixed this in PR #120 and it seems to be working fine.

**Comment by brainwatcher** [comment]
@TheAmid Thank you for your fixing. Where could I download this fixed file? Or waiting for merging in master branch?

**Comment by TheAmid** [comment]
Another place with string conversion. Sorry for that, I fixed it one more time.

**Comment by ykoush** [comment]
Sorry, this is from the most recent pathlib migration, should be fixed now by #120. Please pull the updates.
