### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by alexsayal** [OpenNFT/OpenNFT#160]
Hello all,

I was trying to set up OpenNFT in a Python 3.8.6 conda environment but an error occurs during installation:

```
Collecting git+https://github.com/OpenNFT/OpenNFT.git
  Cloning https://github.com/OpenNFT/OpenNFT.git to /private/var/folders/nd/bgqkn02j7sl982jdtqhts9z00000gn/T/pip-req-build-cj6kty81
  Running command git clone --filter=blob:none --quiet https://github.com/OpenNFT/OpenNFT.git /private/var/folders/nd/bgqkn02j7sl982jdtqhts9z00000gn/T/pip-req-build-cj6kty81
  Resolved https://github.com/OpenNFT/OpenNFT.git to commit 30e784adf92c234eeb97efc86c6d72cf449aa9fc
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/nd/bgqkn02j7sl982jdtqhts9z00000gn/T/pip-req-build-cj6kty81/setup.py", line 10, in <module>
          from distutils.core import DistutilsOptionError
      ImportError: cannot import name 'DistutilsOptionError' from 'distutils.core' (/opt/anaconda3/envs/opennft/lib/python3.8/site-packages/setuptools/_distutils/core.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

This happens in macOS 13 and Ubuntu 18. Could you please take a look?

Thank you in advance,

**Comment by tiborauer** [comment]
It is a version issue, and I have also encountered it. The quick fix I to edit https://github.com/OpenNFT/OpenNFT/blob/30e784adf92c234eeb97efc86c6d72cf449aa9fc/setup.py#L10 by changing `distutils.core` to `distutils.errors`.
